public enum Direction {
    IDLE, LEFT, RIGHT, UP, DOWN, 
    NORTHWEST, NORTHEAST, SOUTHEAST, SOUTHWEST,
    HORIZONTAL, VERTICAL;

    public static final Direction[] directions = {LEFT, RIGHT, UP, DOWN, IDLE, NORTHEAST, NORTHWEST, SOUTHEAST, SOUTHWEST};

}